# Generated by Django 3.1.1 on 2021-09-26 04:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_auto_20210917_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReady',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_lng', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('origin_lat', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('origin_address', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('destination_lng', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('destination_lat', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('destination_address', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('customer_ready', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.customerready')),
            ],
        ),
    ]
