# Generated by Django 3.1.1 on 2021-09-27 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210917_0753'),
        ('chat', '0002_driveronline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('is_finished', models.BooleanField(default=False)),
                ('customer_ready', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.customerready')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
