# Generated by Django 3.2.7 on 2021-11-04 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210929_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
